name: MLOPPS
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train and Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip install -r requirement.txt
          python NN.py

      - name: Check Current Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Files:"
          ls -la  # This will list all files and directories, including hidden ones
      
      - name: Create Report
        run: |
          echo "## Model Metrics" > report.md
          cat model_performance.txt >> report.md

      - name: Send Comment
        run: |
          cml-send-comment report.md

