name: MLOPPS
on: [push]

permissions:
  issues: write
  pull-requests: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train and Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Use GITHUB_TOKEN explicitly here
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip install -r requirement.txt
          python NN.py
          
      - name: Create Report
        run: |
          echo "## Model Metrics" > README.md
          cat model_performance.txt >> README.md
          echo "\n## Model Performance" >> README.md  # Embed the PNG file in the report
          echo "Report content:"

          cml-publish mae_plot.png --md >> README.md

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml
      
      - name: Verify cml-send-comment
        run: |
          which cml-send-comment || echo "cml-send-comment not found. Ensure it's installed."
          
      - name: Send Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN is passed
        run: |
          cml comment create README.md --token ${{ secrets.GITHUB_TOKEN }}
